version: '3.9'
volumes:
  postgres_data:
services:
  database:
    hostname: db
    container_name: todo-db
    image: postgres:13.8-alpine
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 20
  todo-api:
    build: .
    container_name: todo-api
    restart: always
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: todo
      DB_PASS: todo
      DB_NAME: todo
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  todo-web:
    container_name: todo-web
    image: quay.io/johschmidtcc/todo-web
    restart: always
    ports:
      - "8000:80"
    environment:
      VUE_APP_API_BASE_URL: http://localhost:8080/api/v1/todo/
    depends_on:
      - todo-api
