apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets-and-config-maps
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets", "configmaps"]
    verbs: ["get"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: todo-api-go
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: todo-api-go-view-secrets-and-config-maps
subjects:
  - kind: ServiceAccount
    name: todo-api-go
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-secrets-and-config-maps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-go
  labels:
    app: todo-api-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-go
  template:
    metadata:
      labels:
        app: todo-api-go
    spec:
      containers:
      - name: todo-api-go
        image: registry.local:5000/todo-api-go
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DB_HOST
          value: todo-db-postgresql.todo-app.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: todo
        - name: DB_NAME
          value: todo
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: todo-db-postgresql
              key: password
      serviceAccountName: todo-api-go
---
kind: Service
apiVersion: v1
metadata:
  name: todo-api-go
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
  type: ClusterIP
  selector:
    app: todo-api-go
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-api-go-ingress
spec:
  rules:
    - host: todo-api-go.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-api-go
                port:
                  number: 80
